server:
   port: 9192

spring:
   h2:
      console:
         enabled: true
   application:
      name: ORDER-SERVICE

eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         default-zone: http://localhost:8761/eureka
   instance: localhost   
